---
- name: Reiniciar IIS y gestionar F5 Pool
  hosts: webservers_rebooteo
  gather_facts: true
  vars:
    # pool_name
    # f5_host
    # f5_user
    # f5_pass
  # Use the same connection info for ALL calls to bigip_pool_member
  vars_files:
    - f5bigip_pool_member_extra_vars
  #module_defaults:
  #  f5networks.f5_modules.bigip_pool_member:
  #    server: "{{ f5_host }}"
  #    user: "{{ f5_user }}"
  #    password: "{{ f5_pass }}"
  #    validate_certs: false
      
  tasks:
    - name: salida
      debug:
        msg:
          - "pool name: {{ pool_name }}"
          - "usuario: {{ f5_user }}"
          - "password: {{ f5_pass }}"
          - "inventory hostname http://{{ inventory_hostname }}"
          - "ip: {{ host_ip }}"
          
    - name: Sacar servidor del pool de F5
      f5networks.f5_modules.bigip_pool_member:
        pool: "{{ pool_name }}"
        host: "{{ host_ip }}"
        provider:
          server: "{{ f5_host }}"
          user: "{{ f5_user }}"
          password: "{{ f5_pass }}"
          validate_certs: false
        port: 8080  # Puerto del servicio IIS
        state: absent
      delegate_to: localhost

    - name: Reiniciar el servicio de IIS en el servidor
      ansible.windows.win_service:
        name: w3svc  # Servicio de IIS
        state: restarted

    - name: Esperar al puerto 80 del server Windows, maximo 1 minuto
      ansible.builtin.wait_for:
        port: 8080
        host: "{{ host_ip }}"
        connect_timeout: 3
        delay: 3
        timeout: 60
      delegate_to: localhost
        
    - name: Hacer una llamada al / del IIS
      ansible.builtin.uri:
        url: "http://{{ host_ip }}:8080"
      delegate_to: localhost

    - name: Ingresar servidor de nuevo al pool de F5
      f5networks.f5_modules.bigip_pool_member:
        pool: "{{ pool_name }}"
        name: "{{ inventory_hostname }}"
        host: "{{ host_ip }}"
        port: 8080  # Puerto del servicio IIS
        provider:
          server: "{{ f5_host }}"
          user: "{{ f5_user }}"
          password: "{{ f5_pass }}"
          validate_certs: false
        state: present
      delegate_to: localhost
